language: php

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

install:
  - composer require typo3/cms="$TYPO3"
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    echo;
    echo "Running unit tests";
    echo;
    echo;
    .Build/bin/phpunit -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit

  - >
    echo;
    echo "Running php lint";
    echo;
    echo;
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

jobs:
  fast_finish: true
  include:
    - stage: test
      php: 7.1
      env: TYPO3=^8.7
    - stage: test
      php: 7.1
      env: TYPO3=^7.6
    - stage: test
      php: 7
      env: TYPO3=^8.7
    - stage: test
      php: 7
      env: TYPO3=^7.6
    - stage: test
      php: 5.6
      env: TYPO3=^7.6
    - stage: test
      php: 5.5
      env: TYPO3=^7.6

    - stage: publish to ter
      php: 7.1
      before_install: skip
      install: skip
      before_script: skip
      script:
        - |
          if [ -n "$TRAVIS_TAG" ] && [ -n "$TYPO3_ORG_USERNAME" ] && [ -n "$TYPO3_ORG_PASSWORD" ]; then
            # Install requirements
            echo
            echo "Preparing upload of release ${TRAVIS_TAG} to TER"
            echo
            echo
            composer install
            composer require --dev helhum/ter-client dev-master

            # Cleanup before we upload
            git reset --hard HEAD && git clean -fx

            # Upload
            TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`
            echo
            echo "Uploading release ${TRAVIS_TAG} to TER"
            echo
            echo
            .Build/bin/ter-client upload jumpurl . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE"
          fi;
